version: "3.8"
services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=express-docker
    depends_on:
      - db

  db:
    container_name: mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  mongodbdata:
